http:
  addr: ":8888"

websocket:
  path: "/hub"

grpc:
  addr: ":9090"

etcd:
  endpoints: "119.29.111.247:2379"
  service: "kim-gate"
  username: "root"
  password: "YourSecurePassword123"
  ttl: "15s"

shutdown:
  timeout: "10s"

signalg:
  ping_interval: "30s"
  ping_timeout: "60s"

redis:
  dsn: "redis://default:sE2g7BQhFRvvurQH0B0d@119.29.111.247:6379/0"
  push_channel: "kim:gateway:push"
