http:
  addr: ":8888"

websocket:
  path: "/hub"

grpc:
  socket: "/tmp/kim-gate.sock"

shutdown:
  timeout: "10s"

signalg:
  ping_interval: "30s"
  ping_timeout: "60s"

redis:
  dsn: "redis://localhost:6379/0"
  push_channel: "kim:gateway:push"
