// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/project-kgo/kim-gate/internal/app"
	"github.com/project-kgo/kim-gate/internal/auth"
	"github.com/project-kgo/kim-gate/internal/config"
	"github.com/project-kgo/kim-gate/internal/data"
	"github.com/project-kgo/kim-gate/internal/gateway"
	"github.com/project-kgo/kim-gate/internal/rpc"
	"log/slog"
)

// Injectors from wire.go:

func Initialize(cfg config.Config, logger *slog.Logger) (*app.App, error) {
	rejectResolver := auth.NewRejectResolver()
	userProvider := auth.NewUserProvider(rejectResolver)
	dataData, err := data.New(cfg, logger)
	if err != nil {
		return nil, err
	}
	serverID, err := gateway.NewServerID()
	if err != nil {
		return nil, err
	}
	string2 := gateway.ServerIDString(serverID)
	userRouteStore, err := data.NewUserRouteStore(cfg, dataData, logger, string2)
	if err != nil {
		return nil, err
	}
	managedHandler, err := gateway.NewSignalGHandler(cfg, logger, userProvider, userRouteStore, serverID)
	if err != nil {
		return nil, err
	}
	hertz := gateway.NewHertzServer(cfg, logger, managedHandler)
	handler := gateway.SignalGHandler(managedHandler)
	gatewayService, err := rpc.NewGatewayService(handler)
	if err != nil {
		return nil, err
	}
	server, err := rpc.NewServer(cfg, gatewayService, logger)
	if err != nil {
		return nil, err
	}
	appApp := app.New(cfg, logger, hertz, server, dataData)
	return appApp, nil
}
