// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kimgate/v1/gateway.proto

package kimgatev1

import (
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendToUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUsersRequest) Reset() {
	*x = SendToUsersRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersRequest) ProtoMessage() {}

func (x *SendToUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersRequest.ProtoReflect.Descriptor instead.
func (*SendToUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SendToUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendToUsersRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToUsersRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionIds []string               `protobuf:"bytes,1,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToConnectionsRequest) Reset() {
	*x = SendToConnectionsRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToConnectionsRequest) ProtoMessage() {}

func (x *SendToConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToConnectionsRequest.ProtoReflect.Descriptor instead.
func (*SendToConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendToConnectionsRequest) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

func (x *SendToConnectionsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToConnectionsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToGroupRequest) Reset() {
	*x = SendToGroupRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToGroupRequest) ProtoMessage() {}

func (x *SendToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToGroupRequest.ProtoReflect.Descriptor instead.
func (*SendToGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SendToGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SendToGroupRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToGroupRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BroadcastRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       int32                  `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Sent          int32                  `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SendResponse) GetMatched() int32 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *SendResponse) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *SendResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineRequest) Reset() {
	*x = GetOnlineRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineRequest) ProtoMessage() {}

func (x *GetOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetOnlineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOnlineRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetOnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        int32                  `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineResponse) Reset() {
	*x = GetOnlineResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineResponse) ProtoMessage() {}

func (x *GetOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetOnlineResponse) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

type GetUserConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConnectionsRequest) Reset() {
	*x = GetUserConnectionsRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConnectionsRequest) ProtoMessage() {}

func (x *GetUserConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserConnectionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *UserConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *UserConnection) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetUserConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*UserConnection      `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConnectionsResponse) Reset() {
	*x = GetUserConnectionsResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConnectionsResponse) ProtoMessage() {}

func (x *GetUserConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserConnectionsResponse) GetConnections() []*UserConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_proto_kimgate_v1_gateway_proto protoreflect.FileDescriptor

var file_proto_kimgate_v1_gateway_proto_rawDesc = buildGatewayRawDesc()

var (
	file_proto_kimgate_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_kimgate_v1_gateway_proto_rawDescData = file_proto_kimgate_v1_gateway_proto_rawDesc
)

func file_proto_kimgate_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_kimgate_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_kimgate_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kimgate_v1_gateway_proto_rawDescData)
	})
	return file_proto_kimgate_v1_gateway_proto_rawDescData
}

var file_proto_kimgate_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_kimgate_v1_gateway_proto_goTypes = []any{
	(*SendToUsersRequest)(nil),         // 0: kimgate.v1.SendToUsersRequest
	(*SendToConnectionsRequest)(nil),   // 1: kimgate.v1.SendToConnectionsRequest
	(*SendToGroupRequest)(nil),         // 2: kimgate.v1.SendToGroupRequest
	(*BroadcastRequest)(nil),           // 3: kimgate.v1.BroadcastRequest
	(*SendResponse)(nil),               // 4: kimgate.v1.SendResponse
	(*GetOnlineRequest)(nil),           // 5: kimgate.v1.GetOnlineRequest
	(*GetOnlineResponse)(nil),          // 6: kimgate.v1.GetOnlineResponse
	(*GetUserConnectionsRequest)(nil),  // 7: kimgate.v1.GetUserConnectionsRequest
	(*UserConnection)(nil),             // 8: kimgate.v1.UserConnection
	(*GetUserConnectionsResponse)(nil), // 9: kimgate.v1.GetUserConnectionsResponse
}
var file_proto_kimgate_v1_gateway_proto_depIdxs = []int32{
	8, // 0: kimgate.v1.GetUserConnectionsResponse.connections:type_name -> kimgate.v1.UserConnection
	0, // 1: kimgate.v1.GatewayService.SendToUsers:input_type -> kimgate.v1.SendToUsersRequest
	1, // 2: kimgate.v1.GatewayService.SendToConnections:input_type -> kimgate.v1.SendToConnectionsRequest
	2, // 3: kimgate.v1.GatewayService.SendToGroup:input_type -> kimgate.v1.SendToGroupRequest
	3, // 4: kimgate.v1.GatewayService.Broadcast:input_type -> kimgate.v1.BroadcastRequest
	5, // 5: kimgate.v1.GatewayService.GetOnline:input_type -> kimgate.v1.GetOnlineRequest
	7, // 6: kimgate.v1.GatewayService.GetUserConnections:input_type -> kimgate.v1.GetUserConnectionsRequest
	4, // 7: kimgate.v1.GatewayService.SendToUsers:output_type -> kimgate.v1.SendResponse
	4, // 8: kimgate.v1.GatewayService.SendToConnections:output_type -> kimgate.v1.SendResponse
	4, // 9: kimgate.v1.GatewayService.SendToGroup:output_type -> kimgate.v1.SendResponse
	4, // 10: kimgate.v1.GatewayService.Broadcast:output_type -> kimgate.v1.SendResponse
	6, // 11: kimgate.v1.GatewayService.GetOnline:output_type -> kimgate.v1.GetOnlineResponse
	9, // 12: kimgate.v1.GatewayService.GetUserConnections:output_type -> kimgate.v1.GetUserConnectionsResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kimgate_v1_gateway_proto_init() }
func file_proto_kimgate_v1_gateway_proto_init() {
	if File_proto_kimgate_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kimgate_v1_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kimgate_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_kimgate_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_kimgate_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_kimgate_v1_gateway_proto = out.File
	file_proto_kimgate_v1_gateway_proto_rawDesc = nil
	file_proto_kimgate_v1_gateway_proto_goTypes = nil
	file_proto_kimgate_v1_gateway_proto_depIdxs = nil
}

func buildGatewayRawDesc() []byte {
	syntax := "proto3"
	labelOptional := descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL
	labelRepeated := descriptorpb.FieldDescriptorProto_LABEL_REPEATED
	typeString := descriptorpb.FieldDescriptorProto_TYPE_STRING
	typeBytes := descriptorpb.FieldDescriptorProto_TYPE_BYTES
	typeInt32 := descriptorpb.FieldDescriptorProto_TYPE_INT32
	typeMessage := descriptorpb.FieldDescriptorProto_TYPE_MESSAGE
	goPackage := "github.com/project-kgo/kim-gate/proto/kimgate/v1;kimgatev1"

	field := func(name string, number int32, label descriptorpb.FieldDescriptorProto_Label, typ descriptorpb.FieldDescriptorProto_Type, jsonName string) *descriptorpb.FieldDescriptorProto {
		return &descriptorpb.FieldDescriptorProto{
			Name:     proto.String(name),
			Number:   proto.Int32(number),
			Label:    &label,
			Type:     &typ,
			JsonName: proto.String(jsonName),
		}
	}
	messageField := func(name string, number int32, label descriptorpb.FieldDescriptorProto_Label, typeName, jsonName string) *descriptorpb.FieldDescriptorProto {
		f := field(name, number, label, typeMessage, jsonName)
		f.TypeName = proto.String(typeName)
		return f
	}
	method := func(name, input, output string) *descriptorpb.MethodDescriptorProto {
		return &descriptorpb.MethodDescriptorProto{
			Name:       proto.String(name),
			InputType:  proto.String(input),
			OutputType: proto.String(output),
		}
	}

	file := &descriptorpb.FileDescriptorProto{
		Name:    proto.String("proto/kimgate/v1/gateway.proto"),
		Package: proto.String("kimgate.v1"),
		Syntax:  &syntax,
		Options: &descriptorpb.FileOptions{GoPackage: &goPackage},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: proto.String("SendToUsersRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("user_ids", 1, labelRepeated, typeString, "userIds"),
					field("method", 2, labelOptional, typeString, "method"),
					field("payload", 3, labelOptional, typeBytes, "payload"),
				},
			},
			{
				Name: proto.String("SendToConnectionsRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("connection_ids", 1, labelRepeated, typeString, "connectionIds"),
					field("method", 2, labelOptional, typeString, "method"),
					field("payload", 3, labelOptional, typeBytes, "payload"),
				},
			},
			{
				Name: proto.String("SendToGroupRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("group", 1, labelOptional, typeString, "group"),
					field("method", 2, labelOptional, typeString, "method"),
					field("payload", 3, labelOptional, typeBytes, "payload"),
				},
			},
			{
				Name: proto.String("BroadcastRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("method", 1, labelOptional, typeString, "method"),
					field("payload", 2, labelOptional, typeBytes, "payload"),
				},
			},
			{
				Name: proto.String("SendResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("matched", 1, labelOptional, typeInt32, "matched"),
					field("sent", 2, labelOptional, typeInt32, "sent"),
					field("failed", 3, labelOptional, typeInt32, "failed"),
					field("error", 4, labelOptional, typeString, "error"),
				},
			},
			{
				Name: proto.String("GetOnlineRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("user_id", 1, labelOptional, typeString, "userId"),
					field("group", 2, labelOptional, typeString, "group"),
				},
			},
			{
				Name: proto.String("GetOnlineResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("online", 1, labelOptional, typeInt32, "online"),
				},
			},
			{
				Name: proto.String("GetUserConnectionsRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("user_id", 1, labelOptional, typeString, "userId"),
				},
			},
			{
				Name: proto.String("UserConnection"),
				Field: []*descriptorpb.FieldDescriptorProto{
					field("connection_id", 1, labelOptional, typeString, "connectionId"),
					field("server_id", 2, labelOptional, typeString, "serverId"),
				},
			},
			{
				Name: proto.String("GetUserConnectionsResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{
					messageField("connections", 1, labelRepeated, ".kimgate.v1.UserConnection", "connections"),
				},
			},
		},
		Service: []*descriptorpb.ServiceDescriptorProto{{
			Name: proto.String("GatewayService"),
			Method: []*descriptorpb.MethodDescriptorProto{
				method("SendToUsers", ".kimgate.v1.SendToUsersRequest", ".kimgate.v1.SendResponse"),
				method("SendToConnections", ".kimgate.v1.SendToConnectionsRequest", ".kimgate.v1.SendResponse"),
				method("SendToGroup", ".kimgate.v1.SendToGroupRequest", ".kimgate.v1.SendResponse"),
				method("Broadcast", ".kimgate.v1.BroadcastRequest", ".kimgate.v1.SendResponse"),
				method("GetOnline", ".kimgate.v1.GetOnlineRequest", ".kimgate.v1.GetOnlineResponse"),
				method("GetUserConnections", ".kimgate.v1.GetUserConnectionsRequest", ".kimgate.v1.GetUserConnectionsResponse"),
			},
		}},
	}
	raw, err := proto.Marshal(file)
	if err != nil {
		panic(err)
	}
	return raw
}
