// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/kimgate/v1/gateway.proto

package kimgatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_SendToUsers_FullMethodName        = "/kimgate.v1.GatewayService/SendToUsers"
	GatewayService_SendToConnections_FullMethodName  = "/kimgate.v1.GatewayService/SendToConnections"
	GatewayService_SendToGroup_FullMethodName        = "/kimgate.v1.GatewayService/SendToGroup"
	GatewayService_Broadcast_FullMethodName          = "/kimgate.v1.GatewayService/Broadcast"
	GatewayService_GetOnline_FullMethodName          = "/kimgate.v1.GatewayService/GetOnline"
	GatewayService_GetUserConnections_FullMethodName = "/kimgate.v1.GatewayService/GetUserConnections"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	SendToUsers(ctx context.Context, in *SendToUsersRequest, opts ...grpc.CallOption) (*SendResponse, error)
	SendToConnections(ctx context.Context, in *SendToConnectionsRequest, opts ...grpc.CallOption) (*SendResponse, error)
	SendToGroup(ctx context.Context, in *SendToGroupRequest, opts ...grpc.CallOption) (*SendResponse, error)
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*SendResponse, error)
	GetOnline(ctx context.Context, in *GetOnlineRequest, opts ...grpc.CallOption) (*GetOnlineResponse, error)
	GetUserConnections(ctx context.Context, in *GetUserConnectionsRequest, opts ...grpc.CallOption) (*GetUserConnectionsResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) SendToUsers(ctx context.Context, in *SendToUsersRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendToUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SendToConnections(ctx context.Context, in *SendToConnectionsRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendToConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SendToGroup(ctx context.Context, in *SendToGroupRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, GatewayService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetOnline(ctx context.Context, in *GetOnlineRequest, opts ...grpc.CallOption) (*GetOnlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlineResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetUserConnections(ctx context.Context, in *GetUserConnectionsRequest, opts ...grpc.CallOption) (*GetUserConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserConnectionsResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetUserConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	SendToUsers(context.Context, *SendToUsersRequest) (*SendResponse, error)
	SendToConnections(context.Context, *SendToConnectionsRequest) (*SendResponse, error)
	SendToGroup(context.Context, *SendToGroupRequest) (*SendResponse, error)
	Broadcast(context.Context, *BroadcastRequest) (*SendResponse, error)
	GetOnline(context.Context, *GetOnlineRequest) (*GetOnlineResponse, error)
	GetUserConnections(context.Context, *GetUserConnectionsRequest) (*GetUserConnectionsResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) SendToUsers(context.Context, *SendToUsersRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToUsers not implemented")
}
func (UnimplementedGatewayServiceServer) SendToConnections(context.Context, *SendToConnectionsRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToConnections not implemented")
}
func (UnimplementedGatewayServiceServer) SendToGroup(context.Context, *SendToGroupRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToGroup not implemented")
}
func (UnimplementedGatewayServiceServer) Broadcast(context.Context, *BroadcastRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedGatewayServiceServer) GetOnline(context.Context, *GetOnlineRequest) (*GetOnlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnline not implemented")
}
func (UnimplementedGatewayServiceServer) GetUserConnections(context.Context, *GetUserConnectionsRequest) (*GetUserConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserConnections not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_SendToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendToUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendToUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendToUsers(ctx, req.(*SendToUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SendToConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendToConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendToConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendToConnections(ctx, req.(*SendToConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SendToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendToGroup(ctx, req.(*SendToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetOnline(ctx, req.(*GetOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetUserConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetUserConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetUserConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetUserConnections(ctx, req.(*GetUserConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kimgate.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToUsers",
			Handler:    _GatewayService_SendToUsers_Handler,
		},
		{
			MethodName: "SendToConnections",
			Handler:    _GatewayService_SendToConnections_Handler,
		},
		{
			MethodName: "SendToGroup",
			Handler:    _GatewayService_SendToGroup_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _GatewayService_Broadcast_Handler,
		},
		{
			MethodName: "GetOnline",
			Handler:    _GatewayService_GetOnline_Handler,
		},
		{
			MethodName: "GetUserConnections",
			Handler:    _GatewayService_GetUserConnections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kimgate/v1/gateway.proto",
}
