// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kimgate/v1/gateway.proto

package kimgatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushTarget int32

const (
	PushTarget_PUSH_TARGET_UNSPECIFIED       PushTarget = 0
	PushTarget_PUSH_TARGET_USERS             PushTarget = 1
	PushTarget_PUSH_TARGET_GROUP             PushTarget = 2
	PushTarget_PUSH_TARGET_BROADCAST         PushTarget = 3
	PushTarget_PUSH_TARGET_CONNECTIONS       PushTarget = 4
	PushTarget_PUSH_TARGET_CLOSE_USERS       PushTarget = 5
	PushTarget_PUSH_TARGET_CLOSE_CONNECTIONS PushTarget = 6
)

// Enum value maps for PushTarget.
var (
	PushTarget_name = map[int32]string{
		0: "PUSH_TARGET_UNSPECIFIED",
		1: "PUSH_TARGET_USERS",
		2: "PUSH_TARGET_GROUP",
		3: "PUSH_TARGET_BROADCAST",
		4: "PUSH_TARGET_CONNECTIONS",
		5: "PUSH_TARGET_CLOSE_USERS",
		6: "PUSH_TARGET_CLOSE_CONNECTIONS",
	}
	PushTarget_value = map[string]int32{
		"PUSH_TARGET_UNSPECIFIED":       0,
		"PUSH_TARGET_USERS":             1,
		"PUSH_TARGET_GROUP":             2,
		"PUSH_TARGET_BROADCAST":         3,
		"PUSH_TARGET_CONNECTIONS":       4,
		"PUSH_TARGET_CLOSE_USERS":       5,
		"PUSH_TARGET_CLOSE_CONNECTIONS": 6,
	}
)

func (x PushTarget) Enum() *PushTarget {
	p := new(PushTarget)
	*p = x
	return p
}

func (x PushTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kimgate_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (PushTarget) Type() protoreflect.EnumType {
	return &file_proto_kimgate_v1_gateway_proto_enumTypes[0]
}

func (x PushTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushTarget.Descriptor instead.
func (PushTarget) EnumDescriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type PushEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        PushTarget             `protobuf:"varint,1,opt,name=target,proto3,enum=kimgate.v1.PushTarget" json:"target,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ConnectionIds []string               `protobuf:"bytes,6,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushEvent) GetTarget() PushTarget {
	if x != nil {
		return x.Target
	}
	return PushTarget_PUSH_TARGET_UNSPECIFIED
}

func (x *PushEvent) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PushEvent) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PushEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PushEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushEvent) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

type SendToUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUsersRequest) Reset() {
	*x = SendToUsersRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersRequest) ProtoMessage() {}

func (x *SendToUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersRequest.ProtoReflect.Descriptor instead.
func (*SendToUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendToUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendToUsersRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToUsersRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionIds []string               `protobuf:"bytes,1,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToConnectionsRequest) Reset() {
	*x = SendToConnectionsRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToConnectionsRequest) ProtoMessage() {}

func (x *SendToConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToConnectionsRequest.ProtoReflect.Descriptor instead.
func (*SendToConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SendToConnectionsRequest) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

func (x *SendToConnectionsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToConnectionsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToGroupRequest) Reset() {
	*x = SendToGroupRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToGroupRequest) ProtoMessage() {}

func (x *SendToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToGroupRequest.ProtoReflect.Descriptor instead.
func (*SendToGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SendToGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SendToGroupRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToGroupRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BroadcastRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reserved for future synchronous delivery reports. Fire-and-forget sends
	// currently return zero values when the event is accepted.
	Matched       int32  `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Sent          int32  `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	Failed        int32  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SendResponse) GetMatched() int32 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *SendResponse) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *SendResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseUsersRequest) Reset() {
	*x = CloseUsersRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseUsersRequest) ProtoMessage() {}

func (x *CloseUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseUsersRequest.ProtoReflect.Descriptor instead.
func (*CloseUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *CloseUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CloseConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionIds []string               `protobuf:"bytes,1,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionsRequest) Reset() {
	*x = CloseConnectionsRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionsRequest) ProtoMessage() {}

func (x *CloseConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionsRequest.ProtoReflect.Descriptor instead.
func (*CloseConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *CloseConnectionsRequest) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

type CloseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reserved for future synchronous close reports. Fire-and-forget closes
	// currently return zero values when the event is accepted.
	Matched       int32  `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Closed        int32  `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	Failed        int32  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *CloseResponse) GetMatched() int32 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *CloseResponse) GetClosed() int32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

func (x *CloseResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *CloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineRequest) Reset() {
	*x = GetOnlineRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineRequest) ProtoMessage() {}

func (x *GetOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GetOnlineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOnlineRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetOnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        int32                  `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineResponse) Reset() {
	*x = GetOnlineResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineResponse) ProtoMessage() {}

func (x *GetOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *GetOnlineResponse) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

type GetUserConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConnectionsRequest) Reset() {
	*x = GetUserConnectionsRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConnectionsRequest) ProtoMessage() {}

func (x *GetUserConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserConnectionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *UserConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *UserConnection) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetUserConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*UserConnection      `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConnectionsResponse) Reset() {
	*x = GetUserConnectionsResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConnectionsResponse) ProtoMessage() {}

func (x *GetUserConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserConnectionsResponse) GetConnections() []*UserConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Br            string                 `protobuf:"bytes,4,opt,name=br,proto3" json:"br,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *GetTokenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTokenRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetTokenRequest) GetBr() string {
	if x != nil {
		return x.Br
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *GetTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_proto_kimgate_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_kimgate_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/kimgate/v1/gateway.proto\x12\n" +
	"kimgate.v1\"\xc5\x01\n" +
	"\tPushEvent\x12.\n" +
	"\x06target\x18\x01 \x01(\x0e2\x16.kimgate.v1.PushTargetR\x06target\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12%\n" +
	"\x0econnection_ids\x18\x06 \x03(\tR\rconnectionIds\"a\n" +
	"\x12SendToUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"s\n" +
	"\x18SendToConnectionsRequest\x12%\n" +
	"\x0econnection_ids\x18\x01 \x03(\tR\rconnectionIds\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\\\n" +
	"\x12SendToGroupRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"D\n" +
	"\x10BroadcastRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"j\n" +
	"\fSendResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\x05R\amatched\x12\x12\n" +
	"\x04sent\x18\x02 \x01(\x05R\x04sent\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\".\n" +
	"\x11CloseUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"@\n" +
	"\x17CloseConnectionsRequest\x12%\n" +
	"\x0econnection_ids\x18\x01 \x03(\tR\rconnectionIds\"o\n" +
	"\rCloseResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\x05R\amatched\x12\x16\n" +
	"\x06closed\x18\x02 \x01(\x05R\x06closed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"A\n" +
	"\x10GetOnlineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"+\n" +
	"\x11GetOnlineResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\x05R\x06online\"4\n" +
	"\x19GetUserConnectionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x0eUserConnection\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"Z\n" +
	"\x1aGetUserConnectionsResponse\x12<\n" +
	"\vconnections\x18\x01 \x03(\v2\x1a.kimgate.v1.UserConnectionR\vconnections\"m\n" +
	"\x0fGetTokenRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x0e\n" +
	"\x02br\x18\x04 \x01(\tR\x02br\"G\n" +
	"\x10GetTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt*\xcf\x01\n" +
	"\n" +
	"PushTarget\x12\x1b\n" +
	"\x17PUSH_TARGET_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PUSH_TARGET_USERS\x10\x01\x12\x15\n" +
	"\x11PUSH_TARGET_GROUP\x10\x02\x12\x19\n" +
	"\x15PUSH_TARGET_BROADCAST\x10\x03\x12\x1b\n" +
	"\x17PUSH_TARGET_CONNECTIONS\x10\x04\x12\x1b\n" +
	"\x17PUSH_TARGET_CLOSE_USERS\x10\x05\x12!\n" +
	"\x1dPUSH_TARGET_CLOSE_CONNECTIONS\x10\x062\xce\x05\n" +
	"\x0eGatewayService\x12G\n" +
	"\vSendToUsers\x12\x1e.kimgate.v1.SendToUsersRequest\x1a\x18.kimgate.v1.SendResponse\x12S\n" +
	"\x11SendToConnections\x12$.kimgate.v1.SendToConnectionsRequest\x1a\x18.kimgate.v1.SendResponse\x12G\n" +
	"\vSendToGroup\x12\x1e.kimgate.v1.SendToGroupRequest\x1a\x18.kimgate.v1.SendResponse\x12C\n" +
	"\tBroadcast\x12\x1c.kimgate.v1.BroadcastRequest\x1a\x18.kimgate.v1.SendResponse\x12F\n" +
	"\n" +
	"CloseUsers\x12\x1d.kimgate.v1.CloseUsersRequest\x1a\x19.kimgate.v1.CloseResponse\x12R\n" +
	"\x10CloseConnections\x12#.kimgate.v1.CloseConnectionsRequest\x1a\x19.kimgate.v1.CloseResponse\x12H\n" +
	"\tGetOnline\x12\x1c.kimgate.v1.GetOnlineRequest\x1a\x1d.kimgate.v1.GetOnlineResponse\x12c\n" +
	"\x12GetUserConnections\x12%.kimgate.v1.GetUserConnectionsRequest\x1a&.kimgate.v1.GetUserConnectionsResponse\x12E\n" +
	"\bGetToken\x12\x1b.kimgate.v1.GetTokenRequest\x1a\x1c.kimgate.v1.GetTokenResponseB<Z:github.com/project-kgo/kim-gate/proto/kimgate/v1;kimgatev1b\x06proto3"

var (
	file_proto_kimgate_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_kimgate_v1_gateway_proto_rawDescData []byte
)

func file_proto_kimgate_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_kimgate_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_kimgate_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kimgate_v1_gateway_proto_rawDesc), len(file_proto_kimgate_v1_gateway_proto_rawDesc)))
	})
	return file_proto_kimgate_v1_gateway_proto_rawDescData
}

var file_proto_kimgate_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kimgate_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_kimgate_v1_gateway_proto_goTypes = []any{
	(PushTarget)(0),                    // 0: kimgate.v1.PushTarget
	(*PushEvent)(nil),                  // 1: kimgate.v1.PushEvent
	(*SendToUsersRequest)(nil),         // 2: kimgate.v1.SendToUsersRequest
	(*SendToConnectionsRequest)(nil),   // 3: kimgate.v1.SendToConnectionsRequest
	(*SendToGroupRequest)(nil),         // 4: kimgate.v1.SendToGroupRequest
	(*BroadcastRequest)(nil),           // 5: kimgate.v1.BroadcastRequest
	(*SendResponse)(nil),               // 6: kimgate.v1.SendResponse
	(*CloseUsersRequest)(nil),          // 7: kimgate.v1.CloseUsersRequest
	(*CloseConnectionsRequest)(nil),    // 8: kimgate.v1.CloseConnectionsRequest
	(*CloseResponse)(nil),              // 9: kimgate.v1.CloseResponse
	(*GetOnlineRequest)(nil),           // 10: kimgate.v1.GetOnlineRequest
	(*GetOnlineResponse)(nil),          // 11: kimgate.v1.GetOnlineResponse
	(*GetUserConnectionsRequest)(nil),  // 12: kimgate.v1.GetUserConnectionsRequest
	(*UserConnection)(nil),             // 13: kimgate.v1.UserConnection
	(*GetUserConnectionsResponse)(nil), // 14: kimgate.v1.GetUserConnectionsResponse
	(*GetTokenRequest)(nil),            // 15: kimgate.v1.GetTokenRequest
	(*GetTokenResponse)(nil),           // 16: kimgate.v1.GetTokenResponse
}
var file_proto_kimgate_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: kimgate.v1.PushEvent.target:type_name -> kimgate.v1.PushTarget
	13, // 1: kimgate.v1.GetUserConnectionsResponse.connections:type_name -> kimgate.v1.UserConnection
	2,  // 2: kimgate.v1.GatewayService.SendToUsers:input_type -> kimgate.v1.SendToUsersRequest
	3,  // 3: kimgate.v1.GatewayService.SendToConnections:input_type -> kimgate.v1.SendToConnectionsRequest
	4,  // 4: kimgate.v1.GatewayService.SendToGroup:input_type -> kimgate.v1.SendToGroupRequest
	5,  // 5: kimgate.v1.GatewayService.Broadcast:input_type -> kimgate.v1.BroadcastRequest
	7,  // 6: kimgate.v1.GatewayService.CloseUsers:input_type -> kimgate.v1.CloseUsersRequest
	8,  // 7: kimgate.v1.GatewayService.CloseConnections:input_type -> kimgate.v1.CloseConnectionsRequest
	10, // 8: kimgate.v1.GatewayService.GetOnline:input_type -> kimgate.v1.GetOnlineRequest
	12, // 9: kimgate.v1.GatewayService.GetUserConnections:input_type -> kimgate.v1.GetUserConnectionsRequest
	15, // 10: kimgate.v1.GatewayService.GetToken:input_type -> kimgate.v1.GetTokenRequest
	6,  // 11: kimgate.v1.GatewayService.SendToUsers:output_type -> kimgate.v1.SendResponse
	6,  // 12: kimgate.v1.GatewayService.SendToConnections:output_type -> kimgate.v1.SendResponse
	6,  // 13: kimgate.v1.GatewayService.SendToGroup:output_type -> kimgate.v1.SendResponse
	6,  // 14: kimgate.v1.GatewayService.Broadcast:output_type -> kimgate.v1.SendResponse
	9,  // 15: kimgate.v1.GatewayService.CloseUsers:output_type -> kimgate.v1.CloseResponse
	9,  // 16: kimgate.v1.GatewayService.CloseConnections:output_type -> kimgate.v1.CloseResponse
	11, // 17: kimgate.v1.GatewayService.GetOnline:output_type -> kimgate.v1.GetOnlineResponse
	14, // 18: kimgate.v1.GatewayService.GetUserConnections:output_type -> kimgate.v1.GetUserConnectionsResponse
	16, // 19: kimgate.v1.GatewayService.GetToken:output_type -> kimgate.v1.GetTokenResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_kimgate_v1_gateway_proto_init() }
func file_proto_kimgate_v1_gateway_proto_init() {
	if File_proto_kimgate_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kimgate_v1_gateway_proto_rawDesc), len(file_proto_kimgate_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kimgate_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_kimgate_v1_gateway_proto_depIdxs,
		EnumInfos:         file_proto_kimgate_v1_gateway_proto_enumTypes,
		MessageInfos:      file_proto_kimgate_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_kimgate_v1_gateway_proto = out.File
	file_proto_kimgate_v1_gateway_proto_goTypes = nil
	file_proto_kimgate_v1_gateway_proto_depIdxs = nil
}
