// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kimgate/v1/gateway.proto

package kimgatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendToUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUsersRequest) Reset() {
	*x = SendToUsersRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUsersRequest) ProtoMessage() {}

func (x *SendToUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUsersRequest.ProtoReflect.Descriptor instead.
func (*SendToUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SendToUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendToUsersRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToUsersRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToGroupRequest) Reset() {
	*x = SendToGroupRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToGroupRequest) ProtoMessage() {}

func (x *SendToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToGroupRequest.ProtoReflect.Descriptor instead.
func (*SendToGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendToGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SendToGroupRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendToGroupRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BroadcastRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       int32                  `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Sent          int32                  `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SendResponse) GetMatched() int32 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *SendResponse) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *SendResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineRequest) Reset() {
	*x = GetOnlineRequest{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineRequest) ProtoMessage() {}

func (x *GetOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnlineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOnlineRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetOnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        int32                  `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineResponse) Reset() {
	*x = GetOnlineResponse{}
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineResponse) ProtoMessage() {}

func (x *GetOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetOnlineResponse) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

var File_proto_kimgate_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_kimgate_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/kimgate/v1/gateway.proto\x12\n" +
	"kimgate.v1\x1a\x19google/protobuf/any.proto\"w\n" +
	"\x12SendToUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\"r\n" +
	"\x12SendToGroupRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\"Z\n" +
	"\x10BroadcastRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\"j\n" +
	"\fSendResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\x05R\amatched\x12\x12\n" +
	"\x04sent\x18\x02 \x01(\x05R\x04sent\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"A\n" +
	"\x10GetOnlineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"+\n" +
	"\x11GetOnlineResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\x05R\x06online2\xb1\x02\n" +
	"\x0eGatewayService\x12G\n" +
	"\vSendToUsers\x12\x1e.kimgate.v1.SendToUsersRequest\x1a\x18.kimgate.v1.SendResponse\x12G\n" +
	"\vSendToGroup\x12\x1e.kimgate.v1.SendToGroupRequest\x1a\x18.kimgate.v1.SendResponse\x12C\n" +
	"\tBroadcast\x12\x1c.kimgate.v1.BroadcastRequest\x1a\x18.kimgate.v1.SendResponse\x12H\n" +
	"\tGetOnline\x12\x1c.kimgate.v1.GetOnlineRequest\x1a\x1d.kimgate.v1.GetOnlineResponseB<Z:github.com/project-kgo/kim-gate/proto/kimgate/v1;kimgatev1b\x06proto3"

var (
	file_proto_kimgate_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_kimgate_v1_gateway_proto_rawDescData []byte
)

func file_proto_kimgate_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_kimgate_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_kimgate_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kimgate_v1_gateway_proto_rawDesc), len(file_proto_kimgate_v1_gateway_proto_rawDesc)))
	})
	return file_proto_kimgate_v1_gateway_proto_rawDescData
}

var file_proto_kimgate_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_kimgate_v1_gateway_proto_goTypes = []any{
	(*SendToUsersRequest)(nil), // 0: kimgate.v1.SendToUsersRequest
	(*SendToGroupRequest)(nil), // 1: kimgate.v1.SendToGroupRequest
	(*BroadcastRequest)(nil),   // 2: kimgate.v1.BroadcastRequest
	(*SendResponse)(nil),       // 3: kimgate.v1.SendResponse
	(*GetOnlineRequest)(nil),   // 4: kimgate.v1.GetOnlineRequest
	(*GetOnlineResponse)(nil),  // 5: kimgate.v1.GetOnlineResponse
	(*anypb.Any)(nil),          // 6: google.protobuf.Any
}
var file_proto_kimgate_v1_gateway_proto_depIdxs = []int32{
	6, // 0: kimgate.v1.SendToUsersRequest.payload:type_name -> google.protobuf.Any
	6, // 1: kimgate.v1.SendToGroupRequest.payload:type_name -> google.protobuf.Any
	6, // 2: kimgate.v1.BroadcastRequest.payload:type_name -> google.protobuf.Any
	0, // 3: kimgate.v1.GatewayService.SendToUsers:input_type -> kimgate.v1.SendToUsersRequest
	1, // 4: kimgate.v1.GatewayService.SendToGroup:input_type -> kimgate.v1.SendToGroupRequest
	2, // 5: kimgate.v1.GatewayService.Broadcast:input_type -> kimgate.v1.BroadcastRequest
	4, // 6: kimgate.v1.GatewayService.GetOnline:input_type -> kimgate.v1.GetOnlineRequest
	3, // 7: kimgate.v1.GatewayService.SendToUsers:output_type -> kimgate.v1.SendResponse
	3, // 8: kimgate.v1.GatewayService.SendToGroup:output_type -> kimgate.v1.SendResponse
	3, // 9: kimgate.v1.GatewayService.Broadcast:output_type -> kimgate.v1.SendResponse
	5, // 10: kimgate.v1.GatewayService.GetOnline:output_type -> kimgate.v1.GetOnlineResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_kimgate_v1_gateway_proto_init() }
func file_proto_kimgate_v1_gateway_proto_init() {
	if File_proto_kimgate_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kimgate_v1_gateway_proto_rawDesc), len(file_proto_kimgate_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kimgate_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_kimgate_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_kimgate_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_kimgate_v1_gateway_proto = out.File
	file_proto_kimgate_v1_gateway_proto_goTypes = nil
	file_proto_kimgate_v1_gateway_proto_depIdxs = nil
}
