// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/kimgate/v1/push_event.proto

package kimgatev1

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushTarget int32

const (
	PushTarget_PUSH_TARGET_UNSPECIFIED       PushTarget = 0
	PushTarget_PUSH_TARGET_USERS             PushTarget = 1
	PushTarget_PUSH_TARGET_GROUP             PushTarget = 2
	PushTarget_PUSH_TARGET_BROADCAST         PushTarget = 3
	PushTarget_PUSH_TARGET_CONNECTIONS       PushTarget = 4
	PushTarget_PUSH_TARGET_CLOSE_USERS       PushTarget = 5
	PushTarget_PUSH_TARGET_CLOSE_CONNECTIONS PushTarget = 6
)

var (
	PushTarget_name = map[int32]string{
		0: "PUSH_TARGET_UNSPECIFIED",
		1: "PUSH_TARGET_USERS",
		2: "PUSH_TARGET_GROUP",
		3: "PUSH_TARGET_BROADCAST",
		4: "PUSH_TARGET_CONNECTIONS",
		5: "PUSH_TARGET_CLOSE_USERS",
		6: "PUSH_TARGET_CLOSE_CONNECTIONS",
	}
	PushTarget_value = map[string]int32{
		"PUSH_TARGET_UNSPECIFIED":       0,
		"PUSH_TARGET_USERS":             1,
		"PUSH_TARGET_GROUP":             2,
		"PUSH_TARGET_BROADCAST":         3,
		"PUSH_TARGET_CONNECTIONS":       4,
		"PUSH_TARGET_CLOSE_USERS":       5,
		"PUSH_TARGET_CLOSE_CONNECTIONS": 6,
	}
)

func (x PushTarget) Enum() *PushTarget {
	p := new(PushTarget)
	*p = x
	return p
}

func (x PushTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kimgate_v1_push_event_proto_enumTypes[0].Descriptor()
}

func (PushTarget) Type() protoreflect.EnumType {
	return &file_proto_kimgate_v1_push_event_proto_enumTypes[0]
}

func (x PushTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushTarget.Descriptor instead.
func (PushTarget) EnumDescriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_push_event_proto_rawDescGZIP(), []int{0}
}

type PushEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target        PushTarget `protobuf:"varint,1,opt,name=target,proto3,enum=kimgate.v1.PushTarget" json:"target,omitempty"`
	UserIds       []string   `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Group         string     `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Method        string     `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte     `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ConnectionIds []string   `protobuf:"bytes,6,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kimgate_v1_push_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kimgate_v1_push_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_proto_kimgate_v1_push_event_proto_rawDescGZIP(), []int{0}
}

func (x *PushEvent) GetTarget() PushTarget {
	if x != nil {
		return x.Target
	}
	return PushTarget_PUSH_TARGET_UNSPECIFIED
}

func (x *PushEvent) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PushEvent) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PushEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PushEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushEvent) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

var File_proto_kimgate_v1_push_event_proto protoreflect.FileDescriptor

var file_proto_kimgate_v1_push_event_proto_rawDesc = buildPushEventRawDesc()

var (
	file_proto_kimgate_v1_push_event_proto_rawDescOnce sync.Once
	file_proto_kimgate_v1_push_event_proto_rawDescData = file_proto_kimgate_v1_push_event_proto_rawDesc
)

func file_proto_kimgate_v1_push_event_proto_rawDescGZIP() []byte {
	file_proto_kimgate_v1_push_event_proto_rawDescOnce.Do(func() {
		file_proto_kimgate_v1_push_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kimgate_v1_push_event_proto_rawDescData)
	})
	return file_proto_kimgate_v1_push_event_proto_rawDescData
}

var file_proto_kimgate_v1_push_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kimgate_v1_push_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_kimgate_v1_push_event_proto_goTypes = []interface{}{
	(PushTarget)(0),
	(*PushEvent)(nil),
}
var file_proto_kimgate_v1_push_event_proto_depIdxs = []int32{
	0, // 0: kimgate.v1.PushEvent.target:type_name -> kimgate.v1.PushTarget
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kimgate_v1_push_event_proto_init() }
func file_proto_kimgate_v1_push_event_proto_init() {
	if File_proto_kimgate_v1_push_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kimgate_v1_push_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kimgate_v1_push_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_kimgate_v1_push_event_proto_goTypes,
		DependencyIndexes: file_proto_kimgate_v1_push_event_proto_depIdxs,
		EnumInfos:         file_proto_kimgate_v1_push_event_proto_enumTypes,
		MessageInfos:      file_proto_kimgate_v1_push_event_proto_msgTypes,
	}.Build()
	File_proto_kimgate_v1_push_event_proto = out.File
	file_proto_kimgate_v1_push_event_proto_rawDesc = nil
	file_proto_kimgate_v1_push_event_proto_goTypes = nil
	file_proto_kimgate_v1_push_event_proto_depIdxs = nil
}

func buildPushEventRawDesc() []byte {
	syntax := "proto3"
	labelOptional := descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL
	labelRepeated := descriptorpb.FieldDescriptorProto_LABEL_REPEATED
	typeEnum := descriptorpb.FieldDescriptorProto_TYPE_ENUM
	typeString := descriptorpb.FieldDescriptorProto_TYPE_STRING
	typeBytes := descriptorpb.FieldDescriptorProto_TYPE_BYTES
	goPackage := "github.com/project-kgo/kim-gate/proto/kimgate/v1;kimgatev1"
	file := &descriptorpb.FileDescriptorProto{
		Name:    proto.String("proto/kimgate/v1/push_event.proto"),
		Package: proto.String("kimgate.v1"),
		Syntax:  &syntax,
		Options: &descriptorpb.FileOptions{GoPackage: &goPackage},
		EnumType: []*descriptorpb.EnumDescriptorProto{{
			Name: proto.String("PushTarget"),
			Value: []*descriptorpb.EnumValueDescriptorProto{
				{Name: proto.String("PUSH_TARGET_UNSPECIFIED"), Number: proto.Int32(0)},
				{Name: proto.String("PUSH_TARGET_USERS"), Number: proto.Int32(1)},
				{Name: proto.String("PUSH_TARGET_GROUP"), Number: proto.Int32(2)},
				{Name: proto.String("PUSH_TARGET_BROADCAST"), Number: proto.Int32(3)},
				{Name: proto.String("PUSH_TARGET_CONNECTIONS"), Number: proto.Int32(4)},
				{Name: proto.String("PUSH_TARGET_CLOSE_USERS"), Number: proto.Int32(5)},
				{Name: proto.String("PUSH_TARGET_CLOSE_CONNECTIONS"), Number: proto.Int32(6)},
			},
		}},
		MessageType: []*descriptorpb.DescriptorProto{{
			Name: proto.String("PushEvent"),
			Field: []*descriptorpb.FieldDescriptorProto{
				{
					Name:     proto.String("target"),
					Number:   proto.Int32(1),
					Label:    &labelOptional,
					Type:     &typeEnum,
					TypeName: proto.String(".kimgate.v1.PushTarget"),
					JsonName: proto.String("target"),
				},
				{
					Name:     proto.String("user_ids"),
					Number:   proto.Int32(2),
					Label:    &labelRepeated,
					Type:     &typeString,
					JsonName: proto.String("userIds"),
				},
				{
					Name:     proto.String("group"),
					Number:   proto.Int32(3),
					Label:    &labelOptional,
					Type:     &typeString,
					JsonName: proto.String("group"),
				},
				{
					Name:     proto.String("method"),
					Number:   proto.Int32(4),
					Label:    &labelOptional,
					Type:     &typeString,
					JsonName: proto.String("method"),
				},
				{
					Name:     proto.String("payload"),
					Number:   proto.Int32(5),
					Label:    &labelOptional,
					Type:     &typeBytes,
					JsonName: proto.String("payload"),
				},
				{
					Name:     proto.String("connection_ids"),
					Number:   proto.Int32(6),
					Label:    &labelRepeated,
					Type:     &typeString,
					JsonName: proto.String("connectionIds"),
				},
			},
		}},
	}
	raw, err := proto.Marshal(file)
	if err != nil {
		panic(err)
	}
	return raw
}
